stages:
  preprocess:
    cmd: python src/data_preprocessing.py > logs/data_preprocessing.log 2>&1
    deps:
      - data/raw/global-data-on-sustainable-energy.csv
      - src/data_preprocessing.py
      - params.yaml
    outs:
      - data/preprocessed/global_sustainable_energy_preprocessed2.csv

  feature_engineering:
    cmd: python src/feature_engineering.py > logs/feature_engineering.log 2>&1
    deps:
      - data/preprocessed/global_sustainable_energy_preprocessed2.csv
      - src/feature_engineering.py
      - params.yaml
    outs:
      - data/preprocessed/train.csv
      - data/preprocessed/test.csv

  model_building:
    cmd: python src/model_building.py > logs/model_building.log 2>&1
    deps:
      - data/preprocessed/train.csv
      - data/preprocessed/test.csv
      - src/model_building.py
      - params.yaml
    outs:
      - model/model.pkl
