stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw/global-data-on-sustainable-energy.csv
    - params.yaml
    outs:
      # --- Make sure this matches params.yaml ---
    - data/preprocessed/global_sustainable_energy_preprocessed2.csv
    - artifacts/imputation_values.json
    - artifacts/ohe_columns.json

  feature_engineering:
    cmd: python src/feature_engineering.py --config params.yaml
    deps:
    - src/feature_engineering.py
    - data/preprocessed/global_sustainable_energy_preprocessed2.csv
    - params.yaml
    outs:
    - data/processed/train.csv
    - data/processed/test.csv
    - artifacts/boxcox_lambdas.json

  train:
    cmd: python src/train.py --config params.yaml
    deps:
    - src/train.py
    - data/processed/train.csv
    - data/processed/test.csv
    - params.yaml
    outs:
    - models_exp   # DVC tracks this whole directory of models
    - reports_exp   # DVC tracks this whole directory of metrics
    - artifacts/scaler.pkl

  select_best:
    cmd: python src/select_best_model.py --config params.yaml
    deps:
    - src/select_best_model.py
    - models_exp   # Depends on all models
    - reports_exp   # Depends on all metrics
    - params.yaml
    outs:
    - model/model.pkl   # The final, single model for the API
    - reports/best_model_summary.json
params:
- reports_exp/ridge/params.yaml
- reports_exp/lasso/params.yaml
- reports_exp/random_forest/params.yaml
metrics:
- reports_exp/ridge/metrics.json
- reports_exp/lasso/metrics.json
- reports_exp/random_forest/metrics.json
plots:
- reports_exp/ridge/plots/metrics:
    x: step
- reports_exp/lasso/plots/metrics:
    x: step
- reports_exp/random_forest/plots/metrics:
    x: step
