name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Or your preferred version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Or your bucket's region

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull DVC data
        run: |
          dvc pull data/raw/global-data-on-sustainable-energy.csv.dvc
          # Pull other stages to use cache if available
          dvc pull -r my-s3-remote --all --glob

      - name: Reproduce the full pipeline
        run: |
          dvc repro select_best
          
      - name: Show DVC experiments
        run: |
          dvc exp show
          
      - name: Push new artifacts to S3
        run: |
          dvc push -r my-s3-remote --all --glob
          
      - name: Commit DVC lock files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dvc.lock params.yaml # Commit lock file and any param changes
          git commit -m "ci: update dvc.lock and metrics" || echo "No changes to commit"
          git push